openapi: 3.0.3
info:
  title: Legato Service Inventory Notification API
  version: 4.0.0-RC
  description: >+
    The Service Order Notification API provides a standardized mechanism for receiving Service Order notifications. The Service Orchestration Function (SOF) posts the Notification events to the Business Application (BUS) listeners that are registered using the Service Order Hub API.

    - MEF Developer Guide Reference : MEF_W99 v1.0

    - TMF API Reference : TMF 638 v18.5.1

    Copyright © MEF 2020. All Rights Reserved

tags:
  - name: serviceNotification
    description: |-
      Mechanism for SOF to publish *Service* notifications to BUS

servers:
  - url: https://{server}:{port}{basePath}
    variables:
      server:
        default: 'mef.net'
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
      basePath:
        default: /mefApi/legato/serviceInventory/v4

paths:

  /listener/serviceCreateNotification:
    post:
      tags:
        - serviceNotification
      operationId: serviceCreateNotification
      summary: Publish Service Create Notification
      description: |-
        Mechanism for SOF to notify registered BUS listeners of
        Service creation event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/inventory/serviceInventorySchema.openapi.yaml?raw=true#/components/schemas/ServiceCreateNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/BadRequest'
        '401':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/Unauthorized'
        '403':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/Forbidden'
        '404':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/NotFound'
        '405':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/MethodNotAllowed'
        '408':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/RequestTimeout'
        '422':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/UnprocessableEntity'
        '500':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/InternalServerError'
        '503':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/ServiceUnavailable'

  /listener/serviceDeleteNotification:
    post:
      tags:
        - serviceNotification
      operationId: serviceDeleteNotification
      summary: Publish Service Deletion Notification
      description: |-
        Mechanism for SOF to notify registered BUS listeners of
        Service deletion event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/inventory/serviceInventorySchema.openapi.yaml?raw=true#/components/schemas/ServiceDeleteNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/BadRequest'
        '401':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/Unauthorized'
        '403':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/Forbidden'
        '404':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/NotFound'
        '405':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/MethodNotAllowed'
        '408':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/RequestTimeout'
        '422':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/UnprocessableEntity'
        '500':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/InternalServerError'
        '503':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/ServiceUnavailable'

  /listener/serviceStateChangeNotification:
    post:
      tags:
        - serviceNotification
      operationId: serviceStateChangeNotification
      summary: Publish Service StateChange Notification
      description: |-
        Mechanism for SOF to notify registered BUS listeners of
        Service state change event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/inventory/serviceInventorySchema.openapi.yaml?raw=true#/components/schemas/ServiceStateChangeNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/BadRequest'
        '401':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/Unauthorized'
        '403':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/Forbidden'
        '404':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/NotFound'
        '405':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/MethodNotAllowed'
        '408':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/RequestTimeout'
        '422':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/UnprocessableEntity'
        '500':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/InternalServerError'
        '503':
          $ref: 'https://github.com/DarioGonzalez-Axians/MEF-LSO-Legato-billie-final/blob/billie-final/serviceApi/common/errorSchema.openapi.yaml?raw=true#/components/responses/ServiceUnavailable'
