openapi: 3.0.2
info:
  title: Legato Service Ordering Notification API
  version: 4.0.0-RC
  description: >+
    The Service Order Notification API provides a standardized mechanism for 
    receiving Service Order notifications. The Service Orchestration Function 
    (SOF) posts the Notification events to the Business Application (BUS) 
    listeners that are registered using the Service Order Hub API.  

    - MEF Developer Guide Reference : MEF_W99 v1.0

    - TMF API Reference : TMF 641 v18.5.1

    Copyright © MEF 2020. All Rights Reserved

tags:
  - name: serviceOrderNotification
    description: |-
      Mechanism for SOF to publish *ServiceOrder* notifications to BUS

servers:
  - url: https://{server}:{port}{basePath}
    variables:
      server:
        default: 'mef.net' 
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
      basePath:
        default: /mefApi/legato/serviceOrdering/v4
  
paths:
  /listener/serviceOrderCreateNotification:
    post:
      tags:
        - serviceOrderNotification
      operationId: serviceOrderCreateNotification
      summary: Publish ServiceOrder Create Notification
      description: |-
        Mechanism for SOF to notify registred BUS listeners of ServiceOrder  
        creation event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'serviceOrderingSchema.openapi.yaml#/components/schemas/ServiceOrderCreateNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/NotFound'
        '405':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed'
        '408':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/RequestTimeout'
        '422':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/InternalServerError'
        '503':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable'

  /listener/serviceOrderStateChangeNotification:
    post:
      tags:
        - serviceOrderNotification
      operationId: serviceOrderStateChangeNotification
      summary: Publish ServiceOrder StateChange Notification
      description: |-
        Mechanism for SOF to notify registred BUS listeners of ServiceOrder  
        state change event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'serviceOrderingSchema.openapi.yaml#/components/schemas/ServiceOrderStateChangeNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/NotFound'
        '405':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed'
        '408':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/RequestTimeout'
        '422':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/InternalServerError'
        '503':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable'
  
  /listener/serviceOrderItemStateChangeNotification:
    post:
      tags:
        - serviceOrderNotification
      operationId: serviceOrderItemStateChangeNotification
      summary: Publish ServiceOrderItem StateChange Notification
      description: |-
        Mechanism for SOF to notify registred BUS listeners of ServiceOrderItem 
        state-change event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'serviceOrderingSchema.openapi.yaml#/components/schemas/ServiceOrderItemStateChangeNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/NotFound'
        '405':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed'
        '408':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/RequestTimeout'
        '422':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/InternalServerError'
        '503':
          $ref: '../../serviceCommon/v4/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable'
