openapi: 3.0.2
info:
  title: Legato Service Inventory Management API
  version: "MEF_W99_v0.2.0"
  description: >+
    **Legato Service Inventory Management API**
    </p>
    Query information about instantiated services

paths:
  /service:
    get:
      tags:
        - Service
      operationId: serviceFind
      summary: List services
      description: >-
        This operation list service entities. 
        Attribute selection is restricted. 
        fields attribute may be used to filter retrieved attribute(s) for each
        service
      deprecated: false
      parameters:
        - name: relatedParty.id
          required: false
          in: query
          description: ''
          schema:
            type: string
        - name: serviceSpecification.id
          required: false
          in: query
          description: ''
          schema:
            type: string
        - name: serviceSpecification.name
          required: false
          in: query
          description: ''
          schema:
            type: string
        - name: id
          required: false
          in: query
          description: ''
          schema:
            type: string
        - name: fields
          required: false
          in: query
          description: ''
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'commonComponents.yaml#/components/schemas/Service'
        '400':
          description: |-
            Bad Request

            List of supported error codes:
            - 20: Invalid URL parameter value
            - 21: Missing body
            - 22: Invalid body
            - 23: Missing body field
            - 24: Invalid body field
            - 25: Missing header
            - 26: Invalid header value
            - 27: Missing query-string parameter
            - 28: Invalid query-string parameter value
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '401':
          description: |-
            Unauthorized

            List of supported error codes:
            - 40: Missing credentials
            - 41: Invalid credentials
            - 42: Expired credentials
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '403':
          description: |-
            Forbidden

            List of supported error codes:
            - 50: Access denied
            - 51: Forbidden requester
            - 52: Forbidden user
            - 53: Too many requests
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '404':
          description: |-
            Not Found

            List of supported error codes:
            - 60: Resource not found
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '405':
          description: |-
            Method Not Allowed

            List of supported error codes:
            - 61: Method not allowed
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '408':
          description: |-
            Request Time-out

            List of supported error codes:
            - 63: Request time-out
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '422':
          description: |-
            Unprocessable entity

            Functional error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '500':
          description: |-
            Internal Server Error

            List of supported error codes:
            - 1: Internal error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '503':
          description: |+
            Service Unavailable

          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
  '/service/{id}':
    get:
      tags:
        - Service
      operationId: serviceGet
      summary: Retrieve a service
      description: |-
        This operation retrieves a service entity. 
        Attribute selection is enabled for all first level attributes.
      deprecated: false
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/Service'
        '400':
          description: |-
            Bad Request

            List of supported error codes:
            - 20: Invalid URL parameter value
            - 21: Missing body
            - 22: Invalid body
            - 23: Missing body field
            - 24: Invalid body field
            - 25: Missing header
            - 26: Invalid header value
            - 27: Missing query-string parameter
            - 28: Invalid query-string parameter value
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '401':
          description: |-
            Unauthorized

            List of supported error codes:
            - 40: Missing credentials
            - 41: Invalid credentials
            - 42: Expired credentials
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '403':
          description: |-
            Forbidden

            List of supported error codes:
            - 50: Access denied
            - 51: Forbidden requester
            - 52: Forbidden user
            - 53: Too many requests
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '404':
          description: |-
            Not Found

            List of supported error codes:
            - 60: Resource not found
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '422':
          description: |-
            Unprocessable entity

            Functional error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '500':
          description: |-
            Internal Server Error

            List of supported error codes:
            - 1: Internal error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '503':
          description: |-
            Service Unavailable

            List of supported error codes:
            - 5: The service is temporarily unavailable
            - 6: Orange API is over capacity, retry later !
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'