openapi: 3.0.0
info:
  title: Legato Service Catalog Management API
  version: "MEF_W99_v0.2.0"
  description: >+
    **Legato Service Catalog Management API**
    </p>
    Only operation GET (by id & byList) for serviceSpecification is
    supported
  
paths:
  /serviceSpecification:
    get:
      tags:
        - ServiceSpecification
      operationId: serviceSpecificationFind
      summary: List service specifications
      description: >-
        This operation returns service specifications from a catalog.

        Only a predefined set of attribute is proposed : Based on SDC
        limitations, only attributes category and distributionStatus are
        available for serviceSpecification filtering

        Fields attribute could be used to filter attributes retrieved
      deprecated: false
      parameters:
        - name: fields
          required: false
          in: query
          description: Field selection - used to filtering the attributes to be retreived
          schema:
            type: string
        - name: category
          required: false
          in: query
          description: Service Category (filter)
          schema:
            type: string
        - name: distributionStatus
          required: false
          in: query
          description: Service distribution status (filter)
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'commonComponents.yaml#/components/schemas/ServiceSpecification'
        '400':
          description: |-
            Bad Request

            List of supported error codes:
            - 20: Invalid URL parameter value
            - 21: Missing body
            - 22: Invalid body
            - 23: Missing body field
            - 24: Invalid body field
            - 25: Missing header
            - 26: Invalid header value
            - 27: Missing query-string parameter
            - 28: Invalid query-string parameter value
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '401':
          description: |-
            Unauthorized

            List of supported error codes:
            - 40: Missing credentials
            - 41: Invalid credentials
            - 42: Expired credentials
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '403':
          description: |-
            Forbidden

            List of supported error codes:
            - 50: Access denied
            - 51: Forbidden requester
            - 52: Forbidden user
            - 53: Too many requests
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '404':
          description: |-
            Not Found

            List of supported error codes:
            - 60: Resource not found
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '422':
          description: |-
            Unprocessable entity

            Functional error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '500':
          description: |-
            Internal Server Error

            List of supported error codes:
            - 1: Internal error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '503':
          description: |-
            Service Unavailable

            List of supported error codes:
            - 5: The service is temporarily unavailable
            - 6: Orange API is over capacity, retry later !
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
  '/serviceSpecification/{id}':
    get:
      tags:
        - ServiceSpecification
      operationId: serviceSpecificationGet
      summary: Retrieve a service specification
      description: >-
        This operation returns a service specification by its id from a catalog.
        Attribute selection is enabled using the fields attribute.
      deprecated: false
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
        - name: fields
          required: false
          in: query
          description: Attribute selection
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ServiceSpecification'
        '400':
          description: |-
            Bad Request

            List of supported error codes:
            - 20: Invalid URL parameter value
            - 21: Missing body
            - 22: Invalid body
            - 23: Missing body field
            - 24: Invalid body field
            - 25: Missing header
            - 26: Invalid header value
            - 27: Missing query-string parameter
            - 28: Invalid query-string parameter value
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '401':
          description: |-
            Unauthorized

            List of supported error codes:
            - 40: Missing credentials
            - 41: Invalid credentials
            - 42: Expired credentials
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '403':
          description: |-
            Forbidden

            List of supported error codes:
            - 50: Access denied
            - 51: Forbidden requester
            - 52: Forbidden user
            - 53: Too many requests
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '404':
          description: |-
            Not Found

            List of supported error codes:
            - 60: Resource not found
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '422':
          description: |-
            Unprocessable entity

            Functional error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '500':
          description: |-
            Internal Server Error

            List of supported error codes:
            - 1: Internal error
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
        '503':
          description: |-
            Service Unavailable

            List of supported error codes:
            - 5: The service is temporarily unavailable
            - 6: Orange API is over capacity, retry later !
          content:
            application/json;charset=utf-8:
              schema:
                $ref: 'commonComponents.yaml#/components/schemas/ErrorRepresentation'
